spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/ByteTouch/taco
                    default-label: main
                    search-paths: properties

server:
    port: 8888