spring:
    application:
        name: ingredient-api
    jpa:
        hibernate:
            ddl-auto: none
    cloud:
        config:
            uri: http://localhost:8888
    dataSource:
        url: jdbc:h2:mem:testdb
        username: sa
        data: classpath:data.sql
    h2:
        console: 
            enabled: true