spring:
    application:
        name: ingredient-api
    config:
        import: optional:configserver:http://localhost:8888
    jpa:
        hibernate:
            ddl-auto: none
    dataSource:
        url: jdbc:h2:mem:testdb
        username: sa
        data: classpath:data.sql
    h2:
        console: 
            enabled: true

management:
    endpoints:
        web:
            base-path: /actuator
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: always

info:
    author: Wan Cheng
    email: j18467tw@edu.tuis.ac.jp