eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

server:
    port: 0   
    
spring:
#    rabbitmq:
#        host: 192.168.4.77
#        port: 5672
#        username: TacoCloud
#        password: changeme
    kafka:
        bootstrap-servers:
        - 172.18.0.3:9092
    security:
        user:
            name: admin
            password: letmein

management:
    endpoints:
        web:
            base-path: /actuator
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: always

info:
    author: Wan Cheng
    email: j18467tw@edu.tuis.ac.jp