eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

server:
    port: 0   
    
spring:
    rabbitmq:
        host: http://192.168.4.78
        port: 5672
        username: TacoCloud
        password: changeme