server:
    port: 8000

spring:
    application:
        name: admin
    security:
        user:
            name: admin
            password: letmein

eureka:
    instance:
        leaseRenewalIntervalInSeconds: 10
        health-check-url-path: /actuator/health
        metadata-map:
            startup: ${random.int}
    client:
        registry-fetch-interval-seconds: 5
        service-url:
            defaultZone: http://localhost:8761/eureka

management:
    endpoints:
        web:
            base-path: /actuator
            exposure:
                include: health, info
    endpoint:
        health:
            show-details: always

info:
    author: Wan Cheng
    email: j18467tw@edu.tuis.ac.jp