spring:
    application:
        name: service-registry

eureka:
    instance:
        hostname: localhost
        metadata-map:
            user:
                name: admin
                password: letmein
    server:
        enable-self-preservation: false
    client:
        fetch-registry: false
        register-with-eureka: false
        service-url:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

server:
    port: 8761

management:
    endpoints:
        web:
            base-path: /actuator
            exposure:
                include: health, info
    endpoint:
        health:
            show-details: always

info:
    author: Wan Cheng
    email: j18467tw@edu.tuis.ac.jp