spring:
    application:
        name: client

server:
    port: 8080

eureka:
    instance:
        hostname: localhost
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
    
