spring:
    application:
        name: client
    config:
        import: optional:configserver:http://localhost:8888
    
management:
    endpoints:
        web:
            base-path: /actuator
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: always